application: motorrijweer
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: 2.6

builtins:
- appstats: on
# - deferred: on

handlers:
# - url: /
#   static_files: index.html
#   upload: index\.html

- url: /static/(.*\.(gif|png|jpg|ico|js|css|html|txt))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|js|css|html|txt))
  expiration: "28d"

- url: /favicon.ico
  static_files: static/favicon.ico
  expiration: "28d"
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  expiration: "28d"
  upload: static/robots.txt

- url: /.*
  script: wsgi.app

- url: /tasks/.*
  script: wsgi.app
  login: admin

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^static/images/icons
- ^temp/
